
## Api Mercadolivre service

## Server Properties

logging:
  level:
    org:
     springframework:
      #root: DEBUG
      security: DEBUG
      web: DEBUG
      #boot: DEBUG
      cloud: DEBUG
      #integration: DEBUG 
      mvc:
       log-request-details: DEBUG
 
spring:
 application:
  name: br-flower-boot-auth
 mail:
  host: smtp.gmail.com
  port: 465
  username: revendascerta@gmail.com
  password: edu5521d
  properties:
   mail:
    smtp:
     auth: true
     port: 465
     host: smtp.gmail.com
     connectiontimeout: 5000
     timeout: 5000
     writetimeout: 5000
     ssl: 
      enable: true
     starttls:
      required: true
      enable: true
     socketFactory:
      port: 465
      fallback: false
      class: javax.net.ssl.SSLSocketFactory
 jpa.open-in-view: false
 jpa:
  # Show or not log for each sql query
  show-sql: true
  open-in-view: false
  properties:
   # Hibernate Properties
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    ddl-auto: update
    show_sql: true
    format_sql: false
# Banco de dados APP
 datasource:
  url: jdbc:postgresql://localhost:5435/md_carrolucrativo?currentSchema=public&useSSL=false
  username: postgres
  password: admin
  driverClassName: org.postgresql.Driver
  initialization-mode: always

 #date:
  #format:
  # br-sp: uuuu-MM-dd'T'HH:mm:ss+0300 
   
   
api:
  sendreport:
    uri: www.repor.com.br
  version: 2.0
  